spring:
  activemq:
    in-memory: false
    user: admin
    password: admin
    #    broker-url: tcp://192.168.10.28:61616
    broker-url: tcp://127.0.0.1:61616
  datasource:
    #SqlServer数据库配置192.168.21.165   #monitor_360(数据库测试各种图片)
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=monitor_test
    username: sa
    password: command
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

robot:
  mapFile: C:\Users\tianjie_liang\Desktop\task.xmap
